*
* VT100 SCREEN DRIVER STUB (FOR "TTY" INTERFACE)
*
	ORG	OSUTIL
VT100	LDX	ISTPTR		GET INPUT STRING POINTER
	SSR	23		OUTPUT TO TERMINAL
	RTS
* OUTPUT TRANSLATION TABLES
ISTPTR	FDB	TTYPTR1		INITIALIZATION STRING
GXYPTR	FDB	TTYPTR2		GOTO X-Y HANDLER
PUTTAB	FDB	TTYPTR3		CLEAR SCREEN
	FDB	TTYPTR4		CLEAR END OF LINE
	FDB	TTYPTR5		CLEAR END OF DISPLAY
	FDB	TTYPTR6		SPECIAL EFFECTS ON
	FDB	TTYPTR7		SPECIAL EFFECTS OFF
	FDB	TTYPTR8		SCROLL FORWARD
* STANDARD TERMINAL KEYS INPUT LOOKUP TABLE
GETKTAB	FCB	$1B,'[','A',0	CURSOR UP
	FCB	$1B,'[','B',0	CURSOR DOWN
	FCB	$1B,'[','C',0	CURSOR RIGHT
	FCB	$1B,'[','D',0	CURSOR LEFT
	FCB	$1B,'O','w',0	PAGE UP
	FCB	$1B,'O','x',0	PAGE DOWN
	FCB	$1B,'O','u',0	PAGE RIGHT
	FCB	$1B,'O','t',0	PAGE LEFT
	FCB	$1B,'O','P',0	HOME
	FCB	$1B,'O','Q',0	END
	FCB	$08,0		DELETE CHAR
	FCB	$7F,0		DELETE PREVIOUS
	FCB	$1B,'O','n',0	CLEAR SCREEN
* FUNCTION KEYS INPUT LOOKUP TABLES
	FCB	$1B,'O','M',0	F1
	FCB	$1B,'O','l',0	F2
	FCB	$0A,0		F3
	FCB	$1B,'O','v',0	F4
	FCB	$1B,'O','s',0	F5
	FCB	$1B,'O','y',0	F6
	FCB	$1B,'O','p',0	F7
	FCB	$1B,'O','S',0	F8
	FCB	$1B,'O','R',0	F9
	FCB	$1B,'O','m',0	F10
	FCB	$1B,'O','q',0	F11
	FCB	$1B,'O','r',0	F12
	FCB	$1B,'1',0	F13
	FCB	$1B,'2',0	F14
	FCB	$1B,'3',0	F15
	FCB	0		END OF TABLE
* OUTPUT STRINGS
TTYPTR1	FCB	$1B,'=',0
TTYPTR2	FCB	$1B,'[',%11100000,1,';',%10100000,1,'H',0,0,0
TTYPTR3	FCB	$1B,'[','H',$1B,'[','J',0
TTYPTR4	FCB	$1B,'[','K',0
TTYPTR5	FCB	$1B,'[','J',0
TTYPTR6	FCB	$1B,'[','7','m',0
TTYPTR7	FCB	$1B,'[','0','m',0
TTYPTR8	FCB	$1B,'[','2','4',';','1','H',$0A,0
